/**
 * Real data sourced from the verified Google Business Profile screenshot supplied by the user.
 * Never add testimonial quotes, ratings, or coverage-area claims that weren't actually supplied.
 */
export const business = {
  name: "L.T.E. Plumbing Services Ltd",
  initials: "LTE",
  phone: "07985 774899",
  phoneHref: "tel:+447985774899",
  whatsappHref: "https://wa.me/447985774899",
  category: "Plumber",
  rating: 5.0,
  reviewCount: 46,
  emergency247: true,
  highlights: ["24-hour emergency call-out", "Rapid response", "Hot tub specialists", "46 Google reviews"],
  description:
    "L.T.E. Plumbing Services Ltd covers everything from day-to-day plumbing repairs and blocked drains to full bathroom renovations, boiler and heating work, and specialist hot tub servicing — with a rapid-response, 24-hour emergency call-out.",
  services: [
    { id: "emergency", title: "Emergency Call-Out", copy: "Rapid response, 24 hours a day — plumbing emergencies don't wait for office hours." },
    { id: "blocked-drains", title: "Blocked Drains", copy: "Blocked toilets, sinks, baths and showers — cleared fast, done properly." },
    { id: "bathroom", title: "Bathroom Renovation", copy: "Full bathroom installation, renovation and refurbishment, including wall splash panels and tiling." },
    { id: "heating", title: "Boiler & Heating", copy: "Radiator installation and repair, water pump repairs, and thermostat work." },
    { id: "hot-tub", title: "Hot Tub Servicing", copy: "Diagnosis, fault-finding, servicing and repair — pumps, jets, lights and pipework." },
    { id: "maintenance", title: "Property Maintenance", copy: "Tiling, flooring, painting & decorating, carpentry and minor electrical works." },
  ],
  /** Every service line item from the Google listing, verbatim. */
  allServices: [
    "Tap repair",
    "Rapid response",
    "24 hours Emergency call out",
    "Plumbing repairs",
    "General plumbing",
    "Blocked toilets",
    "Block sinks",
    "Block bath",
    "Blocked showers",
    "Bathroom and Kitchen plumbing",
    "Pipe fitter",
    "Water Mains / Pipe replacement",
    "Shower Installation",
    "Radiator Installation",
    "Water Pumps Repair",
    "Radiator Thermostat",
    "Bathroom Renovation",
    "Bathroom Refurbishment",
    "Bathroom Wall Splash Panels",
    "Tiling",
    "Flooring",
    "Painting & Decorating",
    "Carpentry & Joinery",
    "Minor Electrical Works",
    "Overflow work support for businesses and contractors",
    "Property Maintenance",
    "Hot Tub repair (completed in Essex)",
    "Hot Tub servicing",
    "Hot Tub diagnose and fault finding",
    "Pump, jet, light and pipework replacements",
  ],
} as const;
